---
- include_vars: server.yml

- name: Allow REST through UFW
  ufw: proto=tcp port={{ openbazaar_rest_port }} rule=allow
- name: Allow WebSockets through UFW
  ufw: proto=tcp port={{ openbazaar_websocket_port }} rule=allow
- name: Allow Heartbeat through UFW
  ufw: proto=tcp port={{ openbazaar_heartbeat_port }} rule=allow

- name: Install Config
  template:
    src=ob.cfg.j2
    dest={{ openbazaar_user_home_directory }}/ob.cfg
    owner={{ openbazaar_user }}
    group={{ openbazaar_group }}
    mode=0644
  notify:
    - restart server

- name: Install upstart script
  template:
    src=server/openbazaar_upstart.conf.j2
    dest=/etc/init/openbazaard.conf
    owner={{ openbazaar_user }}
    group={{ openbazaar_group }}
    mode=0644
  notify:
    - restart server

- name: Start Server
  service: name=openbazaard state=started
